import fs from 'node:fs';
import assert from 'node:assert/strict';
const targets=await(await fetch('http://127.0.0.1:9223/json')).json();const ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map();ws.addEventListener('message',({data})=>{const m=JSON.parse(data);if(pending.has(m.id)){pending.get(m.id)(m.result);pending.delete(m.id)}});const send=(method,params={})=>new Promise(r=>{pending.set(++id,r);ws.send(JSON.stringify({id,method,params}))});const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await send('Page.navigate',{url:'http://127.0.0.1:4173/'});await new Promise(r=>setTimeout(r,350));
for(const section of ['.audience','.learning','.teachers','.reviews']){await evaluate(`document.querySelector('${section}').scrollIntoView()`);await new Promise(r=>setTimeout(r,100));let shot=await send('Page.captureScreenshot');fs.writeFileSync('mobile-'+section.slice(1)+'.png',Buffer.from(shot.data,'base64'));}
await send('Page.navigate',{url:'http://127.0.0.1:4173/test/'});await new Promise(r=>setTimeout(r,300));await evaluate('sessionStorage.clear()');await send('Page.reload');await new Promise(r=>setTimeout(r,300));assert(await evaluate(`(()=>{let radio=document.querySelector('.answer-option input');radio.click();return !document.querySelector('[data-next]').disabled})()`));await evaluate(`document.querySelector('[data-next]').click()`);await new Promise(r=>setTimeout(r,150));assert.equal(await evaluate(`document.querySelector('[data-question-number]').textContent`),'2');console.log('PASS mobile answer selection and next question');
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:4173/'});await new Promise(r=>setTimeout(r,350));const dimensions=`JSON.stringify([...document.querySelectorAll('header,main,footer')].map(e=>[e.offsetWidth,e.offsetHeight]))`;const before=await evaluate(dimensions);await evaluate(`document.querySelector('link[href*="mobile.css"]').disabled=true`);assert.equal(await evaluate(dimensions),before);console.log('PASS desktop geometry unchanged by mobile styles');ws.close();
